version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "2345:5432"
    networks:
      - postgres
    restart: unless-stopped

  # Very useful for postgres debugging, just open this URL and done:
  # http://localhost:8080/?pgsql=postgres
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres

  # # If we want to use pgadmin - it has nice UI but only arm64
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:6.0
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   volumes:
  #      - pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
